# Generated by Django 5.2.4 on 2026-02-26 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0002_employerprofile_about_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='highest_degree',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='university',
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='college',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='flat_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='house_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='other_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('branch_location', models.CharField(blank=True, max_length=150)),
                ('hiring_responsibility', models.CharField(blank=True, max_length=150)),
                ('experience_years', models.CharField(choices=[('Fresher', 'Fresher'), ('1-3', '1 – 3 Years'), ('3-5', '3 – 5 Years'), ('5+', '5+ Years')], max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=100)),
                ('head_office', models.CharField(blank=True, max_length=150)),
                ('about_company', models.TextField(blank=True)),
                ('company_website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
