# Generated by Django 5.2.4 on 2026-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0003_remove_seekerprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
