# Generated by Django 5.2.4 on 2026-02-26 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0004_employer_is_completed_seekerprofile_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='branch_location',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='hiring_responsibility',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='official_email',
        ),
        migrations.AlterField(
            model_name='employer',
            name='about_company',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_size',
            field=models.CharField(choices=[('SM', 'Small (1-50)'), ('MD', 'Medium (50-250)'), ('LG', 'Large (250-1000)'), ('ENT', 'Enterprise (1000+)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='head_office',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('LAW', 'Law Firm'), ('FIN', 'Finance'), ('HC', 'Healthcare'), ('EDU', 'Education'), ('MKT', 'Marketing'), ('OTH', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
