# Generated by Django 5.2.4 on 2026-02-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0005_remove_employer_branch_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='is_completed',
            new_name='hr_completed',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='about_company',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='head_office',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='industry',
        ),
        migrations.AddField(
            model_name='employer',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('LAW', 'Law Firm'), ('FIN', 'Finance'), ('HC', 'Healthcare'), ('EDU', 'Education'), ('MKT', 'Marketing'), ('OTH', 'Other')], max_length=50)),
                ('company_size', models.CharField(choices=[('SM', 'Small (1-50)'), ('MD', 'Medium (50-250)'), ('LG', 'Large (250-1000)'), ('ENT', 'Enterprise (1000+)')], max_length=50)),
                ('head_office', models.CharField(max_length=150)),
                ('about_company', models.TextField()),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='cruiteapp.employer')),
            ],
        ),
    ]
