# Generated by Django 5.2.4 on 2026-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0006_rename_is_completed_employer_hr_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
