# Generated by Django 5.2.4 on 2026-02-26 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0007_employer_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='employer',
        ),
        migrations.AddField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='cruiteapp.companyprofile'),
        ),
    ]
