# Generated by Django 5.2.4 on 2026-02-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0008_remove_companyprofile_employer_employer_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='company',
            new_name='company_name',
        ),
    ]
