# Generated by Django 5.2.4 on 2026-02-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0009_rename_company_employer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='branch_location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
