# Generated by Django 5.2.4 on 2026-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0010_employer_branch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='experience_years',
            field=models.CharField(choices=[('ALL', 'Any'), ('FRE', 'Fresher'), ('13Y', '1-3 Years'), ('35Y', '3-5 Years'), ('5Y', '5+ Years')], default='ALL', max_length=30),
        ),
    ]
