# Generated by Django 5.2.4 on 2026-02-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruiteapp', '0011_employer_experience_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='company_name',
            new_name='company',
        ),
    ]
